### ISSUE TITLE
OMAP Overview table for v1.3 HRA release

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf#72]
Updating https://hubmapconsortium.github.io/ccf/pages/omap.html table with new numbers for OMAP table AS, CT, BP. Please see .csv uploaded here. 
I've put both the OLD numbers from v1.2 release and new numbers for v1.3 release.

[OMAP3rd-4threleaseNumbers.csv](https://github.com/hubmapconsortium/ccf/files/10222206/OMAP3rd-4threleaseNumbers.csv)

**Comment by bherr2** [comment]
@bhushankhope these are the new numbers for the HRA Portal's OMAP page. Please implement and let us know when it's merged.

**Comment by bherr2** [comment]
Implemented at https://humanatlas.io/omap
